services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=poc
    ports:
      - '5432:5432'
#    volumes:
#      - ./etc/db/data:/var/lib/postgresql/data